export const currency = "EUR";

export const countriesListData: {
  name: string;
  code: string;
  flag: string;
}[] = [
  { name: "Albania", code: "AL", flag: "🇦🇱" },
  { name: "Andorra", code: "AD", flag: "🇦🇩" },
  { name: "Austria", code: "AT", flag: "🇦🇹" },
  { name: "Azerbaijan", code: "AZ", flag: "🇦🇿" },
  { name: "Belgium", code: "BE", flag: "🇧🇪" },
  { name: "Bosnia and Herzegovina", code: "BA", flag: "🇧🇦" },
  { name: "Bulgaria", code: "BG", flag: "🇧🇬" },
  { name: "Croatia", code: "HR", flag: "🇭🇷" },
  { name: "Cyprus", code: "CY", flag: "🇨🇾" },
  { name: "Czech Republic", code: "CZ", flag: "🇨🇿" },
  { name: "Denmark", code: "DK", flag: "🇩🇰" },
  { name: "Estonia", code: "EE", flag: "🇪🇪" },
  { name: "Faroe Islands", code: "FO", flag: "🇫🇴" },
  { name: "Finland", code: "FI", flag: "🇫🇮" },
  { name: "France", code: "FR", flag: "🇫🇷" },
  { name: "Georgia", code: "GE", flag: "🇬🇪" },
  { name: "Germany", code: "DE", flag: "🇩🇪" },
  { name: "Gibraltar", code: "GI", flag: "🇬🇮" },
  { name: "Greece", code: "GR", flag: "🇬🇷" },
  { name: "Greenland", code: "GL", flag: "🇬🇱" },
  { name: "Hungary", code: "HU", flag: "🇭🇺" },
  { name: "Iceland", code: "IS", flag: "🇮🇸" },
  { name: "Ireland", code: "IE", flag: "🇮🇪" },
  { name: "Italy", code: "IT", flag: "🇮🇹" },
  { name: "Kazakhstan", code: "KZ", flag: "🇰🇿" },
  { name: "Kosovo", code: "XK", flag: "🇽🇰" },
  { name: "Latvia", code: "LV", flag: "🇱🇻" },
  { name: "Liechtenstein", code: "LI", flag: "🇱🇮" },
  { name: "Lithuania", code: "LT", flag: "🇱🇹" },
  { name: "Luxembourg", code: "LU", flag: "🇱🇺" },
  { name: "Malta", code: "MT", flag: "🇲🇹" },
  { name: "Monaco", code: "MC", flag: "🇲🇨" },
  { name: "Montenegro", code: "ME", flag: "🇲🇪" },
  { name: "Netherlands", code: "NL", flag: "🇳🇱" },
  { name: "North Macedonia", code: "MK", flag: "🇲🇰" },
  { name: "Norway", code: "NO", flag: "🇳🇴" },
  { name: "Poland", code: "PL", flag: "🇵🇱" },
  { name: "Portugal", code: "PT", flag: "🇵🇹" },
  { name: "Romania", code: "RO", flag: "🇷🇴" },
  { name: "San Marino", code: "SM", flag: "🇸🇲" },
  { name: "Serbia", code: "RS", flag: "🇷🇸" },
  { name: "Slovakia", code: "SK", flag: "🇸🇰" },
  { name: "Slovenia", code: "SI", flag: "🇸🇮" },
  { name: "Spain", code: "ES", flag: "🇪🇸" },
  { name: "Sweden", code: "SE", flag: "🇸🇪" },
  { name: "Switzerland", code: "CH", flag: "🇨🇭" },
  { name: "Turkey", code: "TR", flag: "🇹🇷" },
  { name: "Ukraine", code: "UA", flag: "🇺🇦" },
  { name: "United Kingdom", code: "GB", flag: "🇬🇧" },
  { name: "Vatican City", code: "VA", flag: "🇻🇦" },
  { name: "Isle of Man", code: "IM", flag: "🇮🇲" },
  { name: "Ivory Coast", code: "CI", flag: "🇨🇮" },
  { name: "Mauritania", code: "MR", flag: "🇲🇷" },
  { name: "Morocco", code: "MA", flag: "🇲🇦" },
  { name: "Tunisia", code: "TN", flag: "🇹🇳" },
  { name: "Jordan", code: "JO", flag: "🇯🇴" },
  { name: "Kuwait", code: "KW", flag: "🇰🇼" },
  { name: "Lebanon", code: "LB", flag: "🇱🇧" },
  { name: "United Arab Emirates", code: "AE", flag: "🇦🇪" },
  { name: "Saudi Arabia", code: "SA", flag: "🇸🇦" },
  { name: "Israel", code: "IL", flag: "🇮🇱" },
  { name: "Brazil", code: "BR", flag: "🇧🇷" },
  { name: "Pakistan", code: "PK", flag: "🇵🇰" },
];
