name: Main pipeline

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    types: [ labeled, synchronize ]
  workflow_dispatch:
    inputs:
      name:
        default: "prod"
        description: "Enter dynamic env name or leave default for release"

jobs:
  main_pipeline:
    uses: xdatagroup/cicd-reusable-workflows/.github/workflows/a-base.yaml@workload
    secrets: inherit
    with:
      appName: web-app
      # Project level global variables 
      projectName: comcora
      ciRunner: k8s-default
      dockerBuildArgs: --build-arg NEXT_PUBLIC_BASE_URL=api.comcora.dev
      testEnabled: false
      dockerRegistryRegion: europe-central2
      dockerPlatforms: linux/amd64
      dockerContext: .
      dockerFile: ./Dockerfile
      appBuildType: docker
