import { type AccountCurrencyCode } from "@/types/local.types";

export const currencyDesigns: Record<AccountCurrencyCode, string> = {
  USD: "24/Colored/Dollar",
  EUR: "24/Colored/Euro",
  GBP: "24/Colored/Pound",
  JPY: "24/Colored/Yen",
  INR: "24/Colored/Rupee",
  KRW: "24/Colored/Won",
  AUD: "24/Colored/Dollar",
  CAD: "24/Colored/Dollar",
  CHF: "24/Colored/Franc",
  CNY: "24/Colored/Yuan",
  NZD: "24/Colored/Dollar",
  SGD: "24/Colored/Dollar",
  HKD: "24/Colored/Dollar",
  ZAR: "24/Colored/Rand",
  MXN: "24/Colored/Peso",
  SEK: "24/Colored/Krona",
  DKK: "24/Colored/Krone",
  PLN: "24/Colored/Zloty",
  TRY: "24/Colored/Turkish Lira",
  BRL: "24/Colored/Brazilian Real",
  RUB: "24/Colored",
  NOK: "24/Colored/Krone",
};
