export const mockTodayTransactionData = [
  {
    name: "Теле 2",
    amount: "-300.00",
    data: "Оплата товаров и услуг",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364adhbzfhdhb",
    thumbnail: "",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
  {
    name: "Кафе",
    amount: "-150.00",
    data: "Оплата товаров и услуг",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364qerf",
    thumbnail: "К",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
  {
    name: "Роман К.",
    amount: "-16500.00",
    data: "Перевод клиенту Comcora",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364adh",
    thumbnail: "",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
];

export const mockYesterdayTransactionData = [
  {
    name: "Deluxe Wine",
    amount: "-200.14",
    data: "Оплата товаров и услуг",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364dsfh",
    thumbnail: "DW",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
  {
    name: "Роман К.",
    amount: "-16500.00",
    data: "Перевод клиенту Comcora",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364asfgdcDZV",
    thumbnail: "",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
  {
    name: "Пивной дворик",
    amount: "-200.14",
    data: "Оплата товаров и услуг",
    id: "8ef41f11-feb3-4880-9119-bc519ace4364dshddth",
    thumbnail: "ПД",
    date: "17 сентября 2023, 18:21",
    phone: "+72344335",
    senderAccountNumber: "112741735375627365",
    receiverAccountNumber: "112741735375627365",
    message:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit sed diam nonumy eirmod er at liber",
  },
];

export const days = Array.from({ length: 31 }, (_, i) => i + 1);

export const paymentDay = [
  { id: 1, label: "Выбранный день", value: "selectedDay" },
  { id: 2, label: "Срок оплаты", value: "dueDate" },
  { id: 3, label: "Дата получения счёта", value: "invoiceDate" },
];

export const paymentMethods = [
  { id: 1, label: "Автоматически", value: "automatic" },
  { id: 2, label: "Вручную", value: "manual" },
];

export const mockInvoice = {
  id: 1,
  amount: 300,
  currency: "€",
  senderAccountNumber: "EE00 6547 8754 9874 0092",
  beneficiary: {
    thumbnail: "",
    name: "COMCORA LIFE INSURANCE SE",
    accountNumber: "EE00 6547 8754 9874 3456",
    linkNumber: "64765765765",
    description: "Insurance agency",
  },
};

export const mockUser = {
  id: 2,
  name: "Artur Selivanov Selivanov",
  avatar: "",
  status: "offline",
  amount: "32,05",
  currency: "€",
  date: "12 сентября",
  type: "incoming",
  accountNumber: "EE90 0009 8889 7765 7890",
  beneficiaryAccountNumber: "EE90 0009 8889 7765 7890",
};

export const mockUsersData = [
  {
    id: 1,
    name: "Konstantin Selivanov",
    avatar:
      "https://tbbapps-g0a5hdaxead3hffh.z01.azurefd.net/profile-pictures/5d91b41d-affe-468b-ace0-fe197067dcb0",
    status: "online",
    amount: "60",
    currency: "€",
    date: "11 сентября",
    type: "outgoing",
    accountNumber: "EE90 0009 8889 7765 7890",
  },
  {
    id: 2,
    name: "Artur Selivanov Selivanov",
    avatar: "",
    status: "offline",
    amount: "32,05",
    currency: "€",
    date: "12 сентября",
    type: "incoming",
    accountNumber: "EE90 0009 8889 7765 7890",
  },
  {
    id: 3,
    name: "Aleksander Laur",
    avatar: "",
    status: "online",
    amount: "32,05",
    currency: "€",
    date: "12 сентября",
    type: "outgoing",
    accountNumber: "EE90 0009 8889 7765 7890",
  },
  {
    id: 4,
    name: "Tele 2",
    avatar:
      "https://tbbapps-g0a5hdaxead3hffh.z01.azurefd.net/profile-pictures/5d91b41d-affe-468b-ace0-fe197067dcb0",
    status: "online",
    amount: "11,25",
    currency: "€",
    date: "13 сентября",
    type: "incoming",
    accountNumber: "EE90 0009 8889 7765 7890",
  },
];

export const mockBankData = [
  {
    id: 1,
    name: "LHV",
    logo: "",
    accountNumber: "EE90 0009 8889 7765 7890",
  },
];

export const mockRequstMoneyLink =
  "https://www.comcora.com/results?search_query=%D0%B7%D0%B0%D0%BF%D1%80%D0%BE%D1%81+%D0%B4%D0%B5%D0%BD%D0%B5%D0%B3+%D0%B2+%D1%81%D0%B1%D0%B5%D1%80%D0%B1%D0%B0%D0%BD%D0%BA+%D1%81+%D0%BA%D0%BE%D0%BC%D0%BF%D1%8C%D1%8E%D1%82%D0%B5%D1%80%D0%B0";

export const mockCurrencies = [
  {
    id: "usd",
    value: "USD",
    label: "United States Dollar",
    symbol: "$",
    flag: "🇺🇸",
    flagValue: "US",
  },
  {
    id: "eur",
    value: "EUR",
    label: "Euro",
    symbol: "€",
    flag: "🇪🇺",
    flagValue: "EU",
  },
  {
    id: "gbp",
    value: "GBP",
    label: "British Pound Sterling",
    symbol: "£",
    flag: "🇬🇧",
    flagValue: "GB",
  },
  {
    id: "jpy",
    value: "JPY",
    label: "Japanese Yen",
    symbol: "¥",
    flag: "🇯🇵",
    flagValue: "JP",
  },
  {
    id: "aud",
    value: "AUD",
    label: "Australian Dollar",
    symbol: "A$",
    flag: "🇦🇺",
    flagValue: "AU",
  },
  {
    id: "cad",
    value: "CAD",
    label: "Canadian Dollar",
    symbol: "C$",
    flag: "🇨🇦",
    flagValue: "CA",
  },
  {
    id: "chf",
    value: "CHF",
    label: "Swiss Franc",
    symbol: "CHF",
    flag: "🇨🇭",
    flagValue: "CH",
  },
  {
    id: "cny",
    value: "CNY",
    label: "Chinese Yuan",
    symbol: "¥",
    flag: "🇨🇳",
    flagValue: "CN",
  },
  {
    id: "inr",
    value: "INR",
    label: "Indian Rupee",
    symbol: "₹",
    flag: "🇮🇳",
    flagValue: "IN",
  },
  {
    id: "brl",
    value: "BRL",
    label: "Brazilian Real",
    symbol: "R$",
    flag: "🇧🇷",
    flagValue: "BR",
  },
];

export const mockCountries = [
  { id: "al", value: "AL", flag: "🇦🇱", label: "Albania" },
  { id: "ad", value: "AD", flag: "🇦🇩", label: "Andorra" },
  { id: "at", value: "AT", flag: "🇦🇹", label: "Austria" },
  { id: "az", value: "AZ", flag: "🇦🇿", label: "Azerbaijan" },
  { id: "be", value: "BE", flag: "🇧🇪", label: "Belgium" },
  { id: "ba", value: "BA", flag: "🇧🇦", label: "Bosnia and Herzegovina" },
  { id: "bg", value: "BG", flag: "🇧🇬", label: "Bulgaria" },
  { id: "hr", value: "HR", flag: "🇭🇷", label: "Croatia" },
  { id: "cy", value: "CY", flag: "🇨🇾", label: "Cyprus" },
  { id: "cz", value: "CZ", flag: "🇨🇿", label: "Czech Republic" },
  { id: "dk", value: "DK", flag: "🇩🇰", label: "Denmark" },
  { id: "ee", value: "EE", flag: "🇪🇪", label: "Estonia" },
  { id: "fo", value: "FO", flag: "🇫🇴", label: "Faroe Islands" },
  { id: "fi", value: "FI", flag: "🇫🇮", label: "Finland" },
  { id: "fr", value: "FR", flag: "🇫🇷", label: "France" },
  { id: "ge", value: "GE", flag: "🇬🇪", label: "Georgia" },
  { id: "de", value: "DE", flag: "🇩🇪", label: "Germany" },
  { id: "gi", value: "GI", flag: "🇬🇮", label: "Gibraltar" },
  { id: "gr", value: "GR", flag: "🇬🇷", label: "Greece" },
  { id: "gl", value: "GL", flag: "🇬🇱", label: "Greenland" },
  { id: "hu", value: "HU", flag: "🇭🇺", label: "Hungary" },
  { id: "is", value: "IS", flag: "🇮🇸", label: "Iceland" },
  { id: "ie", value: "IE", flag: "🇮🇪", label: "Ireland" },
  { id: "it", value: "IT", flag: "🇮🇹", label: "Italy" },
  { id: "kz", value: "KZ", flag: "🇰🇿", label: "Kazakhstan" },
  { id: "xk", value: "XK", flag: "🇽🇰", label: "Kosovo" },
  { id: "lv", value: "LV", flag: "🇱🇻", label: "Latvia" },
  { id: "li", value: "LI", flag: "🇱🇮", label: "Liechtenstein" },
  { id: "lt", value: "LT", flag: "🇱🇹", label: "Lithuania" },
  { id: "lu", value: "LU", flag: "🇱🇺", label: "Luxembourg" },
  { id: "mt", value: "MT", flag: "🇲🇹", label: "Malta" },
  { id: "mc", value: "MC", flag: "🇲🇨", label: "Monaco" },
  { id: "me", value: "ME", flag: "🇲🇪", label: "Montenegro" },
  { id: "nl", value: "NL", flag: "🇳🇱", label: "Netherlands" },
  { id: "mk", value: "MK", flag: "🇲🇰", label: "North Macedonia" },
  { id: "no", value: "NO", flag: "🇳🇴", label: "Norway" },
  { id: "pl", value: "PL", flag: "🇵🇱", label: "Poland" },
  { id: "pt", value: "PT", flag: "🇵🇹", label: "Portugal" },
  { id: "ro", value: "RO", flag: "🇷🇴", label: "Romania" },
  { id: "sm", value: "SM", flag: "🇸🇲", label: "San Marino" },
  { id: "rs", value: "RS", flag: "🇷🇸", label: "Serbia" },
  { id: "sk", value: "SK", flag: "🇸🇰", label: "Slovakia" },
  { id: "si", value: "SI", flag: "🇸🇮", label: "Slovenia" },
  { id: "es", value: "ES", flag: "🇪🇸", label: "Spain" },
  { id: "se", value: "SE", flag: "🇸🇪", label: "Sweden" },
  { id: "ch", value: "CH", flag: "🇨🇭", label: "Switzerland" },
  { id: "tr", value: "TR", flag: "🇹🇷", label: "Turkey" },
  { id: "ua", value: "UA", flag: "🇺🇦", label: "Ukraine" },
  { id: "gb", value: "GB", flag: "🇬🇧", label: "United Kingdom" },
  { id: "va", value: "VA", flag: "🇻🇦", label: "Vatican City" },
  { id: "im", value: "IM", flag: "🇮🇲", label: "Isle of Man" },
  { id: "ci", value: "CI", flag: "🇨🇮", label: "Ivory Coast" },
  { id: "mr", value: "MR", flag: "🇲🇷", label: "Mauritania" },
  { id: "ma", value: "MA", flag: "🇲🇦", label: "Morocco" },
  { id: "tn", value: "TN", flag: "🇹🇳", label: "Tunisia" },
  { id: "jo", value: "JO", flag: "🇯🇴", label: "Jordan" },
  { id: "kw", value: "KW", flag: "🇰🇼", label: "Kuwait" },
  { id: "lb", value: "LB", flag: "🇱🇧", label: "Lebanon" },
  { id: "ae", value: "AE", flag: "🇦🇪", label: "United Arab Emirates" },
  { id: "sa", value: "SA", flag: "🇸🇦", label: "Saudi Arabia" },
  { id: "il", value: "IL", flag: "🇮🇱", label: "Israel" },
  { id: "br", value: "BR", flag: "🇧🇷", label: "Brazil" },
  { id: "pk", value: "PK", flag: "🇵🇰", label: "Pakistan" },
];
