name: UI Tests (Docker)

on: push

jobs:
  ui-tests-docker:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "true"
      BROWSER: "chrome"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Install ChromeDriver (matching Chrome version)
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
            jq -r '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -q "$DRIVER_URL" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
      
      
      - name: Build Docker image
        run: |
         cd comcora-web-app-main
         docker build \
         --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
         --build-arg NEXT_PUBLIC_BASE_URL=http://localhost:3000 \
         --build-arg SESSION_SECRET=secret \
         --build-arg NPM_TOKEN=${{ secrets.TEST }}
          -t comcora-web-production .

      

      - name: Run Docker container
        run: |
          docker run -d -p 3000:3000 --name comcora-app comcora-web-production

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:3000/en; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to start... ($i)"
            sleep 2
          done

      - name: Run UI tests
        run: pytest --maxfail=1 --disable-warnings -v

      - name: Cleanup Docker container
        if: always()
        run: |
          docker stop comcora-app
          docker rm comcora-app
