- name: Build Docker image
  run: |
    cd comcora-web-app-main
    docker build -t comcora-web-production . \
      --build-arg NEXT_PUBLIC_BASE_URL=http://localhost:3000 \
      --build-arg SESSION_SECRET=secret

- name: Run Docker container
  run: |
    docker run -d -p 3000:3000 --name comcora-app comcora-web-production

- name: Wait for app to be ready
  run: |
    for i in {1..30}; do
      if curl -fs http://localhost:3000/en; then
        echo "App is ready!"
        break
      fi
      echo "Waiting for app to start... ($i)"
      sleep 2
    done

- name: Run tests
  run: pytest --maxfail=1 --disable-warnings -v
