name: Automated tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Change to '11' if needed

      - name: Download Allure CLI (latest)
        run: |
          LATEST_URL=$(curl -s https://api.github.com/repos/allure-framework/allure2/releases/latest \
            | grep "browser_download_url.*tgz" \
            | cut -d '"' -f 4)
          wget "$LATEST_URL" -O allure.tgz
          tar -xvzf allure.tgz
          DIR_NAME=$(tar -tf allure.tgz | head -1 | cut -f1 -d"/")
          sudo mv "$DIR_NAME" /opt/allure
          sudo ln -s /opt/allure/bin/allure /usr/bin/allure

      - name: Run tests and generate Allure results
        run: |
          pytest -n 1 --alluredir=allure-results

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Upload Allure report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: allure-report

      - name: Clean up git repo
        run: rm -rf .git

      - name: Configure Git
        run: |
          git config --global user.email "chsargsyan@gmail.com"
          git config --global user.name "christqa"


