name: UI Tests (Docker)

on:
  push:
    branches:
      - main
      - develop

jobs:
  ui-tests-docker:
    runs-on: ubuntu-latest
    env:
      HEADLESS: "true"
      BROWSER: "chrome"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies for Chrome and utilities
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg unzip jq

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver (matching Chrome version)
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          echo "Detected Chrome version: $CHROME_VERSION"
          DRIVER_URL=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/last-known-good-versions-with-downloads.json | \
            jq -r --arg ver "$CHROME_VERSION" '.channels.Stable.downloads.chromedriver[] | select(.platform == "linux64") | .url')
          wget -q "$DRIVER_URL" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Build Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_BASE_URL=http://localhost:3000 \
            --build-arg SESSION_SECRET=${{ secrets.SESSION_SECRET }} \
            -t comcora-web-production .

      - name: Run Docker container
        run: docker run -d -p 3000:3000 comcora-web-production

      - name: Wait for app to be ready
        run: |
          for i in {1..30}; do
            if curl -fs http://localhost:3000/en; then
              echo "App is ready!"
              break
            fi
            echo "Waiting for app to start... ($i)"
            sleep 2
          done

      - name: Run UI tests
        run: pytest --maxfail=1 --disable-warnings -v
