name: Automated tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Chrome (v124)
        run: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb

      - name: Install ChromeDriver (v124)
        run: |
          CHROMEDRIVER_VERSION=124.0.6367.91
          wget -q https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/
          sudo chmod +x /usr/local/bin/chromedriver
    

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run tests and generate Allure report
        run: |
          pytest --alluredir=allure-results

      - name: Upload Allure results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/

      - name: Clean up git repo
        run: rm -rf .git

      - name: Configure Git
        run: |
          git config --global user.email "chsargsyan@gmail.com"
          git config --global user.name "christqa"


