name: Artifact Smoke Test

on:
  push:

jobs:
  test:
    runs-on: self-hosted
    env:
      RUNNER_TOOL_CACHE: /Users/christinesargsyan/actions-runner/_toolcache

    steps:
      - name: Ensure cache dir exists
        run: |
          mkdir -p /Users/christinesargsyan/actions-runner/_toolcache
          chmod -R 777 /Users/christinesargsyan/actions-runner/_toolcache

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'none'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run smoke tests
        env:
          BASE_URL: http://comcora.dev
        run: pytest
