name: Artifact Smoke Test

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: setup Python
       uses: actions/setup-python@v4
       with:
         python-version: "3.10"
     - name:  Install Chrome
       run: sudo apt-get install google-chrome-stable
     - name: install dependencies
       run: pip install -r requirements.txt
     - name: Kill old Chrome instances
       run: pkill chrome || true
     - name: Start Selenium container
       run: |
         docker run -d --rm \
           -p 4444:4444 \
           selenium/standalone-chrome:latest

     - name: Run test
       run: pytest

