name: Artifact Smoke Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Build frontend Docker image
        working-directory: frontend
        run: |
          docker build -t comcora-web-production . \
            --build-arg NEXT_PUBLIC_BASE_URL=http://localhost:3000 \
            --build-arg SESSION_SECRET=secret

      - name: Run frontend container
        run: |
          docker run -d --name comcora-frontend -p 3000:3000 comcora-web-production

      - name: Wait for frontend to be available
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:3000 | grep -q "<html"; then
              echo "✅ Frontend is ready"
              break
            fi
            echo "⏳ Waiting for frontend..."
            sleep 3
          done

      - name: Start Selenium Standalone Chrome
        run: |
          docker run -d --rm --name selenium -p 4444:4444 selenium/standalone-chrome:latest

      - name: Wait for Selenium to be available
        run: |
          for i in {1..15}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "✅ Selenium is ready"
              break
            fi
            echo "⏳ Waiting for Selenium..."
            sleep 3
          done

      - name: Run smoke tests
        env:
          BASE_URL: http://localhost:3000
        run: pytest
