name: Artifact Smoke Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chromium
        ports:
          - 4456:4444
        options: >-
          --shm-size 2g
          --health-cmd "curl -f http://localhost:4444/wd/hub/status || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Start frontend server
        working-directory: comcora-web-app-main
        run: |
          npm run dev 
          sleep 10      
          

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Kill any existing Chrome processes
        run: pkill chrome || true

      - name: Start Selenium Standalone (force x86_64 for multi-arch runners)
        run: |
          docker run -d --rm --platform linux/amd64 -p 4444:4444 selenium/standalone-chrome:latest


      - name: Wait for Selenium to become available
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:4444/wd/hub/status | grep -q '"ready":true'; then
              echo "✅ Selenium is ready"
              break
            fi
            echo "⏳ Waiting for Selenium..."
            sleep 3
          done


      - name: Run tests
        env:
          BASE_URL: http://127.0.0.1:3000
        run: pytest
